### ISSUE TITLE
google earth

### ISSUE THREAD

**Issue by caipeng-hrv** [melowntech/vts-browser-js#153]
how can i config google earth map use vts

**Comment by DavidLevinsky** [comment]
I depend in which format is map stored (there were several formats used by Google). It also depend how is map data served. We support maps represented in the form of hierarchical tiles.  Where each tile have size 256x256 pixels.  Images have to be in form of files which can be accessed by url (or file path).  Paths are configured in form templates (e.g. `https://some-server.com/{lod}-{x}-{y}.jpg`). More details can be found at VTS documentation: [https://vts-geospatial.org/](https://vts-geospatial.org/)

**Comment by caipeng-hrv** [comment]
ok,thank you
