### ISSUE TITLE
addPolygon3 fails in webmercator projection

### ISSUE THREAD

**Issue by skazemi** [melowntech/vts-browser-js#160]
Hi,
in webmercator projection config as reference frame, proj becomes undefined and causes exception here:
https://github.com/melowntech/vts-browser-js/blob/9749b5d58da63bdedc77a0784ef82514bbbde833/src/core/map/geodata-builder.js#L1124

**Comment by DavidLevinsky** [comment]
Hi, thanks for contributing. Fix will be merged to the master branch.
