### ISSUE TITLE
Panning the map via script

### ISSUE THREAD

**Issue by coyfi** [melowntech/vts-browser-js#168]
Greetings,

would there be a way to pan the JavaScript VTS map programmatically? With Leaftlet and Google Maps, for example, this can be achieved with their panBy functions. The VTS C++ map has also a "Pan" function as part of its Navigation, but I couldn't find something similar from the JavaScript version. Have I managed to miss it both from the API documentation and code, or is it yet to be implemented? Or would there be there something else that achieves the same functionality?

Thank you.

**Comment by DavidLevinsky** [comment]
Yes you can pan with position. I have updated documentation.

**Comment by coyfi** [comment]
Thank you very much for the quick reply and demo! These solved the issue.
