### ISSUE TITLE
RangeError in GpuGroup.prototype.copyBuffer (v2.21.8 minified)

### ISSUE THREAD

**Issue by skazemi** [melowntech/vts-browser-js#175]
line:
https://github.com/melowntech/vts-browser-js/blob/1823e16ee44d8ae0aedbc97b461235fbc5607843/src/core/renderer/gpu/group.js#L684

`Uncaught RangeError: Invalid typed array length: 671088640`
    `at new Uint8Array (<anonymous>)`
    `at d.copyBuffer (vts-browser.min.js:formatted:26008)`
    `at d.addRenderJob2 (vts-browser.min.js:formatted:26030)`
    `at p.processPackedCommands (vts-browser.min.js:formatted:6053)`
    `at p.onGeodataProcessorMessage (vts-browser.min.js:formatted:6076)`
    `at j.processProcessingTasks (vts-browser.min.js:formatted:18507)`
    `at j.update (vts-browser.min.js:formatted:18542)`
    `at A.onUpdate (vts-browser.min.js:formatted:2423)`

**Comment by davidmtech** [comment]
Can you write me more information about how to replicate this behavior? 671088640 seems like very big number.
