### ISSUE TITLE
TypeError in MapGeodataBuilder.prototype.processHeights (v2.21.8 minified)

### ISSUE THREAD

**Issue by skazemi** [melowntech/vts-browser-js#176]
line: https://github.com/melowntech/vts-browser-js/blob/a598942de4cc23b1c354153087103a919339e27c/src/core/map/geodata-builder.js#L1454

`Uncaught TypeError: Cannot read property 'coords' of null`
    `at c.processHeights (vts-browser.min.js:formatted:15913)`
    `at A.callListener (vts-browser.min.js:formatted:2401)`
    `at j.update (vts-browser.min.js:formatted:18549)`
    `at A.onUpdate (vts-browser.min.js:formatted:2423)`

**Comment by davidmtech** [comment]
Can you send more information about  how to replicate this behavior.  I can test in code whether is "item" variable is defined. But I would like to know how it happen in first place.
