### ISSUE TITLE
 How to draw custom Geometry using a WebGL custom shader.

### ISSUE THREAD

**Issue by SukanyaGavhane** [melowntech/vts-browser-js#181]
Is it possible to draw a custom geometry using a custom shader with WebGL along with vts-browser.js .

**if yes** Can you please share some examples of drawing custom geometry using webgl with vts-browser.js

If it is not available in any of the current releases, is it in the implementation plan in the near future?

**Comment by davidmtech** [comment]
Hello,

there is example how to use custom shaders  for custom geometry:
