### ISSUE TITLE
drawlinestring not rendering on mobile

### ISSUE THREAD

**Issue by jrjdavidson** [melowntech/vts-browser-js#203]
Hello- 

I use the following to draw lines on the map, works fine on a desktop, however the lines don't appear to render on mobile. Any thoughts on where I might be going wrong?

```
 renderer.drawLineString({
                    points : points,
                    size : 2.0,
                    ...color && {color:color},  //white line is multiplied by this color so resulting point will be this color
                    depthTest : false,
                    //depthOffset : [-0.01,0,0],
                    screenSpace : false, //switch to physical space
                    blend : false
                });
```

**Comment by davidmtech** [comment]
Line with color property looks wrong. Try something like `color:[255,0,255,255]` This should draw line with magenta color.

drawLineString should work on mobile devices. Otherwise I would need whole code which demonstrates problem.

**Comment by jrjdavidson** [comment]
No the color works fine- the idea is that it checks that the color variable is not set false or null, and then assigns the color.
I tried on another mobile phone and it works - it seems that my ancient phone isn't able to handle that specific part of the code  but everything else works.
