### ISSUE TITLE
using custom tin mesh and rastor tiles

### ISSUE THREAD

**Issue by ajinra020307** [melowntech/vts-browser-js#204]
Guys thanks for this amazing project,

We have the tin mesh and rastor tile data. Is it possible to use that data to render tiles.?

**Comment by TANK2003** [comment]
+1

**Comment by ladislavhorky** [comment]
Hello @TANK2003 , @ajinra020307 ,

can you be more specific about the question/issue? E.g. : 

What components of VTS are you using?
What format you have the data in? 
What do you mean by "render tiles" (into image, display in VTS browser)?
etc.

Thanks,
Ladislav

**Comment by TANK2003** [comment]
Hello, thanks for your fast answer and your job !

I have two datasets:
- A TMS dataset : is a folder with the z/x/y.png structure 
- A terrain dataset produce with cesuim terrain builder (https://github.com/geo-data/cesium-terrain-builder): is a folder with the z/x/y.terrain structure

All i want is to display those datasets with VTS JS, 

Thanks in advance

**Comment by ladislavhorky** [comment]
Hello @TANK2003 ,

The TMS is perfectly fine, best served through the VTS-mapproxy using `tms-raster-remote` driver - this will serve just configuration, the tiles will be served from whichever URL you provide the on - possibly using Nginx, event the configuration that is part of VTS-backend. In case you have the original georeferenced image/texture, you can use the same approach as for the terrain - see below.

As for cesium terrain, this is not supported by VTS browser. However if you have the original DEM, you can use VTS-mapproxy and `mapproxy-setup-resource`  tool to generate and serve VTS surface tiles on the fly. If your DEM is large, this may even save lots of space on your drive. 

For learning with VTS-backend I recommend any of our [tutorials](https://vts-geospatial.org/tutorials/index.html#backend) - they are a bit dated but still provide all necessary info, `mapproxy-setup-resource` hugely simplifying the most tedious parts.

Hope this helps,
Ladislav
