### ISSUE TITLE
Control over pitch change as you zoom into object?

### ISSUE THREAD

**Issue by jrjdavidson** [melowntech/vts-browser-js#212]
Hi,

In this example, as you zoom in the pitch gradually changes to 90. Is there any way to prevent this behaviour? I
'd like to be able to look at the cliff face when zoom in.

cheers

**Comment by davidmtech** [comment]
You can try `constrainCamera : false` parameter.  

https://jsfiddle.net/2tq7mwud/

or modify source code:
https://github.com/melowntech/vts-browser-js/blob/master/src/browser/control-mode/map-observer.js#L448

**Comment by jrjdavidson** [comment]
That's exactly what I needed thanks! I just re-read my comment and realised i forgot to link the example, sorry
